# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab78906e99bbac74573836fc7237cd8094f100568036ec69161d3831ab7276128f3ba91a81f0329cc36979cc1666f0533b2761bd5330bd90b9a9ac8936289eda

test:
  secret_key_base: fc23223093197a8d21a6ec514153b35d545c2b3cec7faadba87d25c25994a859a8d08e4cb6a428a05b18c1f8fcd0fc68f6377c7381fddb1c416b605b2b807f1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
